//HintName: Contract1.g.cs
// <auto-generated />
#nullable enable

namespace Hubs.InterfaceGenerators;

public class Contract1Impl : global::IContract1
{
    async global::System.Threading.Tasks.Task global::IContract1.Method1() 
    {
        throw new NotImplementedException();
    }

    async global::System.Threading.Tasks.Task global::IContract1.Method2(int i) 
    {
        throw new NotImplementedException();
    }

    async global::System.Threading.Tasks.Task global::IContract1.Method3(object i) 
    {
        throw new NotImplementedException();
    }
}