//HintName: Contract.g.cs
// <auto-generated />
#nullable enable

namespace Hubs.InterfaceGenerators;

public class ContractImpl : global::TestNamespace.IContract
{
    async global::System.Threading.Tasks.Task global::TestNamespace.IContract.Method1() 
    {
        throw new NotImplementedException();
    }

    async global::System.Threading.Tasks.Task global::TestNamespace.IContract.Method2(int i) 
    {
        throw new NotImplementedException();
    }

    async global::System.Threading.Tasks.Task global::TestNamespace.IContract.Method3(object i) 
    {
        throw new NotImplementedException();
    }

    async global::System.Threading.Tasks.Task<int> global::TestNamespace.IContract.Method4() 
    {
        throw new NotImplementedException();
    }

    async global::System.Threading.Tasks.Task<int> global::TestNamespace.IContract.Method5(int i) 
    {
        throw new NotImplementedException();
    }

    async global::System.Threading.Tasks.Task<int> global::TestNamespace.IContract.Method6(object i) 
    {
        throw new NotImplementedException();
    }
}